# Generated by Django 5.1.1 on 2024-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros_rehabilitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='distrito',
            field=models.CharField(default='Uruca', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centro',
            name='provincia',
            field=models.CharField(default='San Jose', max_length=15),
            preserve_default=False,
        ),
    ]
