# Generated by Django 5.1.1 on 2024-10-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_rehabilitacion', '0003_servicios_tratamientos_tratamientosporcentro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
