# Generated by Django 5.1.1 on 2024-10-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros_rehabilitacion', '0004_delete_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientos',
            name='descripcion',
        ),
    ]
